--- 
title: "ML Workflow for Research Scientists"
author: "Ajinkya K Mulay"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: 
description: "This is a tutorial for Google Colab users to contribute code to a well-structured Python project."
---

# Preamble

## Who is this wiki for? {-}

There is a long list of Python and Github workflow tutorials. There are so many Machine Learning Tutorials too. However, there is no one easy to follow Machine Learning-ML Cloud Service-Local Development-Benchmarking Workflow. I am going to talk about three Free services which any person can use with basic internet access - Google Colaboratory (for ML Cloud Service), VS Code (Local ML Development) and Weights and Biases (for benchmarking).
TL;DR- This is a process guide for deploying your ML models as a researcher!

## What won't you learn? {-}

How to code in Python or develop Machine Leaning Models or learn Pytorch.

## What will you learn? {-}

- How to contribute code to a well-structured projects 
- Work with multiple Google Colaboratory Notebooks 
- Create easy Python Documentation
- Scale up as your project and team grows in complexity and size
- Benchmark and Project Tracking
